#!/bin/bash
set -e

# ==============================================================================
# Moodle Backend Docker Entrypoint Script
# ==============================================================================

echo "=============================================="
echo "  Starting Moodle Backend Container"
echo "=============================================="

# ==============================================================================
# Environment Variable Defaults
# ==============================================================================
MOODLE_DBTYPE=${MOODLE_DBTYPE:-pgsql}
MOODLE_DBHOST=${MOODLE_DBHOST:-db}
MOODLE_DBNAME=${MOODLE_DBNAME:-moodle}
MOODLE_DBUSER=${MOODLE_DBUSER:-moodleuser}
MOODLE_DBPASSWORD=${MOODLE_DBPASSWORD:-moodlepass}
MOODLE_DBPORT=${MOODLE_DBPORT:-5432}
MOODLE_DBPREFIX=${MOODLE_DBPREFIX:-mdl_}

MOODLE_WWWROOT=${MOODLE_WWWROOT:-http://localhost}
MOODLEDATA_PATH=${MOODLEDATA_PATH:-/var/www/moodledata}
MOODLE_ADMIN=${MOODLE_ADMIN:-admin}
MOODLE_ADMIN_PASSWORD=${MOODLE_ADMIN_PASSWORD:-Admin123!}
MOODLE_ADMIN_EMAIL=${MOODLE_ADMIN_EMAIL:-admin@example.com}
MOODLE_FULLNAME=${MOODLE_FULLNAME:-My Learning Platform}
MOODLE_SHORTNAME=${MOODLE_SHORTNAME:-LMS}

REDIS_HOST=${REDIS_HOST:-redis}
REDIS_PORT=${REDIS_PORT:-6379}
REDIS_PASSWORD=${REDIS_PASSWORD:-}

MOODLE_SSL_PROXY=${MOODLE_SSL_PROXY:-false}

# Brand Settings (from whitelabel config)
BRAND_NAME=${BRAND_NAME:-MyBrand}

# ==============================================================================
# Wait for Database
# ==============================================================================
echo "[1/5] Waiting for database connection..."
max_tries=30
counter=0

while ! pg_isready -h "$MOODLE_DBHOST" -p "$MOODLE_DBPORT" -U "$MOODLE_DBUSER" -d "$MOODLE_DBNAME" > /dev/null 2>&1; do
    counter=$((counter + 1))
    if [ $counter -ge $max_tries ]; then
        echo "ERROR: Could not connect to database after $max_tries attempts. Exiting."
        exit 1
    fi
    echo "Waiting for database... (attempt $counter/$max_tries)"
    sleep 2
done
echo "Database is ready!"

# ==============================================================================
# Wait for Redis (if configured)
# ==============================================================================
if [ -n "$REDIS_HOST" ]; then
    echo "[2/5] Waiting for Redis connection..."
    counter=0
    max_tries=15
    
    while ! nc -z "$REDIS_HOST" "$REDIS_PORT" > /dev/null 2>&1; do
        counter=$((counter + 1))
        if [ $counter -ge $max_tries ]; then
            echo "WARNING: Could not connect to Redis. Proceeding without Redis..."
            REDIS_HOST=""
            break
        fi
        echo "Waiting for Redis... (attempt $counter/$max_tries)"
        sleep 2
    done
    
    if [ -n "$REDIS_HOST" ]; then
        echo "Redis is ready!"
    fi
else
    echo "[2/5] Redis not configured, skipping..."
fi

# ==============================================================================
# Create/Update Moodle Config
# ==============================================================================
echo "[3/5] Generating Moodle configuration..."

CONFIG_FILE="/var/www/html/config.php"

# Generate config.php from environment variables
cat > "$CONFIG_FILE" << EOF
<?php
// Moodle configuration file - Auto-generated by docker-entrypoint.sh
// DO NOT EDIT MANUALLY - Changes will be overwritten on container restart

unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

// ==============================================================================
// DATABASE CONFIGURATION
// ==============================================================================
\$CFG->dbtype    = '${MOODLE_DBTYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${MOODLE_DBHOST}';
\$CFG->dbname    = '${MOODLE_DBNAME}';
\$CFG->dbuser    = '${MOODLE_DBUSER}';
\$CFG->dbpass    = '${MOODLE_DBPASSWORD}';
\$CFG->prefix    = '${MOODLE_DBPREFIX}';
\$CFG->dboptions = [
    'dbpersist' => false,
    'dbport'    => '${MOODLE_DBPORT}',
    'dbsocket'  => false,
];

// ==============================================================================
// WEB SITE LOCATION
// ==============================================================================
\$CFG->wwwroot   = '${MOODLE_WWWROOT}';
\$CFG->dataroot  = '${MOODLEDATA_PATH}';
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 02777;

// ==============================================================================
// SSL/PROXY CONFIGURATION
// ==============================================================================
EOF

if [ "$MOODLE_SSL_PROXY" = "true" ]; then
    cat >> "$CONFIG_FILE" << 'EOF'
$CFG->sslproxy = true;
$CFG->reverseproxy = true;

// Handle proxy headers
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
    $_SERVER['HTTPS'] = 'on';
}
EOF
fi

# Add Redis configuration if available
if [ -n "$REDIS_HOST" ]; then
    cat >> "$CONFIG_FILE" << EOF

// ==============================================================================
// REDIS SESSION CONFIGURATION
// ==============================================================================
\$CFG->session_handler_class = '\\core\\session\\redis';
\$CFG->session_redis_host = '${REDIS_HOST}';
\$CFG->session_redis_port = ${REDIS_PORT};
EOF

    if [ -n "$REDIS_PASSWORD" ]; then
        echo "\$CFG->session_redis_auth = '${REDIS_PASSWORD}';" >> "$CONFIG_FILE"
    fi

    cat >> "$CONFIG_FILE" << 'EOF'
$CFG->session_redis_database = 0;
$CFG->session_redis_prefix = 'mdl_';
$CFG->session_redis_acquire_lock_timeout = 120;
$CFG->session_redis_lock_expire = 7200;
EOF
fi

# Add performance and security settings
cat >> "$CONFIG_FILE" << 'EOF'

// ==============================================================================
// PERFORMANCE CONFIGURATION
// ==============================================================================
$CFG->cachedir = '/tmp/moodlecache';
$CFG->localcachedir = '/tmp/moodlelocalcache';
$CFG->tempdir = '/tmp/moodletemp';

// ==============================================================================
// SECURITY CONFIGURATION
// ==============================================================================
$CFG->passwordpolicy = true;
$CFG->minpasswordlength = 8;
$CFG->minpassworddigits = 1;
$CFG->minpasswordlower = 1;
$CFG->minpasswordupper = 1;
$CFG->minpasswordnonalphanum = 1;
$CFG->maxeditingtime = 1800;
$CFG->cookiesecure = true;
$CFG->cookiehttponly = true;

// ==============================================================================
// MOBILE APP CONFIGURATION
// ==============================================================================
$CFG->enablemobilewebservice = true;

// ==============================================================================
// THEME CONFIGURATION
// ==============================================================================
$CFG->theme = 'masbrand';
$CFG->allowthemechangeonurl = false;

// ==============================================================================
// DEBUG CONFIGURATION (Production)
// ==============================================================================
@error_reporting(E_ALL | E_STRICT);
@ini_set('display_errors', '0');
$CFG->debug = 0;
$CFG->debugdisplay = 0;
$CFG->perfdebug = 0;

// ==============================================================================
// CRON CONFIGURATION
// ==============================================================================
$CFG->cronclionly = false;
$CFG->cronremotepassword = '';

require_once(__DIR__ . '/public/lib/setup.php');
EOF

echo "Configuration file generated successfully!"

# ==============================================================================
# Create Required Directories
# ==============================================================================
echo "[4/5] Creating required directories..."

mkdir -p "${MOODLEDATA_PATH}"
mkdir -p "${MOODLEDATA_PATH}/temp"
mkdir -p "${MOODLEDATA_PATH}/cache"
mkdir -p "${MOODLEDATA_PATH}/localcache"
mkdir -p "${MOODLEDATA_PATH}/sessions"
mkdir -p "${MOODLEDATA_PATH}/filedir"
mkdir -p "${MOODLEDATA_PATH}/trashdir"
mkdir -p "${MOODLEDATA_PATH}/lang"
mkdir -p /tmp/moodlecache
mkdir -p /tmp/moodlelocalcache
mkdir -p /tmp/moodletemp
mkdir -p /var/log/moodle

# Set permissions
chown -R www-data:www-data "${MOODLEDATA_PATH}"
chown -R www-data:www-data /tmp/moodlecache
chown -R www-data:www-data /tmp/moodlelocalcache
chown -R www-data:www-data /tmp/moodletemp
chown -R www-data:www-data /var/log/moodle
chown -R www-data:www-data /var/www/html
chmod -R 775 "${MOODLEDATA_PATH}"

echo "Directories created and permissions set!"

# ==============================================================================
# Run Moodle Installation if Needed
# ==============================================================================
echo "[5/5] Checking Moodle installation status..."

# Check if Moodle is already installed by checking for the config table
INSTALLED=$(PGPASSWORD="$MOODLE_DBPASSWORD" psql -h "$MOODLE_DBHOST" -p "$MOODLE_DBPORT" -U "$MOODLE_DBUSER" -d "$MOODLE_DBNAME" -tAc "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '${MOODLE_DBPREFIX}config')" 2>/dev/null || echo "f")

if [ "$INSTALLED" = "t" ]; then
    echo "Moodle is already installed. Running upgrade check..."
    cd /var/www/html/public
    sudo -u www-data php admin/cli/upgrade.php --non-interactive || true
    sudo -u www-data php admin/cli/purge_caches.php || true
    echo "Upgrade check complete!"
else
    echo "Moodle is not installed. Starting installation..."
    cd /var/www/html/public
    
    sudo -u www-data php admin/cli/install.php \
        --wwwroot="${MOODLE_WWWROOT}" \
        --dataroot="${MOODLEDATA_PATH}" \
        --dbtype="${MOODLE_DBTYPE}" \
        --dbhost="${MOODLE_DBHOST}" \
        --dbname="${MOODLE_DBNAME}" \
        --dbuser="${MOODLE_DBUSER}" \
        --dbpass="${MOODLE_DBPASSWORD}" \
        --dbport="${MOODLE_DBPORT}" \
        --prefix="${MOODLE_DBPREFIX}" \
        --fullname="${MOODLE_FULLNAME}" \
        --shortname="${MOODLE_SHORTNAME}" \
        --adminuser="${MOODLE_ADMIN}" \
        --adminpass="${MOODLE_ADMIN_PASSWORD}" \
        --adminemail="${MOODLE_ADMIN_EMAIL}" \
        --non-interactive \
        --agree-license || {
            echo "Installation failed, but continuing to allow manual setup..."
        }
    
    echo "Moodle installation complete!"
fi

echo "=============================================="
echo "  Moodle Backend Ready!"
echo "  URL: ${MOODLE_WWWROOT}"
echo "=============================================="

# Start the main process
exec "$@"
